config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts
  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def create
    post = Post.new(post_params)
    # post.title = params[:post][:title]
    # post.content = params[:post][:content]
    post.save
    
    redirect_to '/'
  end

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show

  end

  def update
    @post.update(post_params)    
    # @post.title = params[:post][:title]
    # @post.content = params[:post][:content]
    @post.save
    
    redirect_to '/'
  end

  def edit
  end

  def destroy
    @post.destroy
    
    redirect_to '/'
  end

  private 

  def set_post
    @post = Post.find params[:id]
  end
  
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <title>자유게시판</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-default">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%if user_signed_in? %>
     <ul>
       <li type="button" class="btn btn-success jm"><%= link_to '로그아웃', destroy_user_session_path, method: :delete %></li>
       <li type="button" class="btn btn-success jm"><%= link_to '수정', edit_user_registration_path %></li>
    </ul>
    <% else %>
     <ul>
       <li type="button" class="btn btn-success jm"><%= link_to '회원가입', new_user_registration_path %></li>
       <li type="button" class="btn btn-success jm"><%= link_to '로그인', new_user_session_path %></li>
    </ul>  
    <% end %>
  </nav>
  
  <header>
    <h1 class="title jm">자유게시판</h1>
    <br>
    <h4 class="title jm">하고 싶은 말을 자유롭게 써 봐요</h4>
      <ul class="nav nav-tabs justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="/posts/new">
          <button type="button" class="btn btn-success jm">새 글 쓰기</button></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/posts">
          <button type="button" class="btn btn-success jm">목록</button></a>
        </li>
      </ul>
  </header>
<%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>

app/views/posts/_form.html.erb
<div class="posting">
  <%= form_for(@post) do |f| %>
    <div><%= f.text_field :title, placeholder: "제목을 입력하세요" %></div>
    <br>
    <div><%= f.text_area :content, :rows => '20', :cols => '50', placeholder: "내용을 입력하세요" %></div>
    <%= f.submit '제출' %>
  <% end %>
</div>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<!--<form action = '/posts/update/<%= @post.id %>' method='post'>-->
<!--    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>-->
<!--    <input type='text' name='post_title' value = '<%= @post.title %>'></input>-->
<!--    <textarea name='post_content'><%= @post.content %></textarea>-->
<!--    <input type='submit' value='제출'></input>-->
<!--</form>-->

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container-fluid">
  <table class="table table-striped jm">
    <thead>
      <th scope="col">#</th>
      <th style="width: 10%" scope="col">제목</th>
      <th style="width: 75%"scope="col">내용</th>
      <th style="width: 5%"scope="col"></th>
      <th style="width: 5%"scope="col"></th>
      <th style="width: 5%"scope="col"></th>
    </thead>
     <% @posts.each do |p| %>            
    <tbody>
      <th scope="row"><%= p.id %></th>
      <td><%= p.title %></td>
      <td><%= p.content %></td>
      <td><a href='/posts/<%= p.id %>'><button type="button" class="btn btn-success">보기</button></a></td>
      <!--<td><%= link_to '보기', post_path(id: p.id)%></td>-->
      <td><a href="/posts/<%= p.id %>/edit"><button type="button" class="btn btn-success">수정</button></a></td>
      <td><a href="/posts/<%= p.id %>" data-method='delete' data-confirm='정말로요?' ><button type="button" class="btn btn-success">삭제</button></a></td>
    </tbody>
      <% end %>
  </table>
</div>

app/views/posts/new.html.erb
<!--<form action = '/posts/create/' method='post'>-->
<!--    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>-->
<!--    <input type='text' name='post_title'></input>-->
<!--    <textarea name='post_content'></textarea>-->
<!--    <input type='submit' value='제출'></input>-->
<!--</form>-->

<!--<%= form_tag(posts_path, method: "post") do %>-->
<!--    <%= text_field_tag 'post_title', nil %>-->
<!--    <%= text_area_tag 'post_content', nil %>-->
<!--    <%= submit_tag '제출' %>-->
<!--<% end %>-->

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="showing jm">
  <div><h3> 제목 : <%= @post.title %></h3></div>
  <hr>
  <div><h5><%= @post.content %></h5></div>
</div>